version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2020!"
      MYSQL_DATABASE: "testdb"
    ports:
      - "3306:3306"
    volumes:
      - /home/mysqlvolume:/var/lib/mysql
    networks:
      - my-lovely-docker-network

  adminer:
    image: adminer
    ports:
      - 8070:8080
    networks:
      - my-lovely-docker-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-dev
    command: go run main.go
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/home/apivolume
    networks:
      - my-lovely-docker-network
    depends_on:
      - db

networks:
  my-lovely-docker-network:
    driver: bridge
