package routes //routes/Routes.go

import (
	"api/handlers"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "api/docs" // docs is generated by Swag CLI, you have to import it.
)

//SetupRouter ... Configure routes
func SetupRouter() *gin.Engine {
	r := gin.Default()
	v1 := r.Group("/api")
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	{
		v1.GET("plan", handlers.GetProducts)
		v1.POST("plan", handlers.CreateProducts)
		v1.GET("plan/:id", handlers.GetProductsByID)
		v1.PUT("plan/:id", handlers.UpdateProducts)
		v1.DELETE("plan/:id", handlers.DeleteProducts)
	}
	return r
}
