package routes //routes/Routes.go

import (
	"api/handlers"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "api/docs" // docs is generated by Swag CLI, you have to import it.
)

//SetupRouter ... Configure routes
func SetupRouter() *gin.Engine {
	r := gin.Default()
	v1 := r.Group("/api")

	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	{
		v1.GET("user", handlers.GetUsers)
		v1.POST("user", handlers.CreateUser)
		v1.GET("user/:id", handlers.GetUserByID)
		v1.PUT("user/:id", handlers.UpdateUser)
		v1.DELETE("user/:id", handlers.DeleteUser)
	}
	return r
}
